name: Deploy Databricks Notebook Job

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
    secrets:
      host:
        required: true
      pat:
        required: true
      azure_credentials:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "abi-databricks-${{ inputs.env_name }}"

    steps:
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0

      - name: Download src files
        uses: actions/download-artifact@v3
        with:
          name: src_artifacts
          path: src/

      - name: databricks-import-directory
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          # Databricks host
          databricks-host: ${{ secrets.host }}
          # Databricks token
          databricks-token: ${{ secrets.pat }}
          # LOCAL_NOTEBOOKS_PATH
          local-path: src/
          # REMOTE_NOTEBOOK_PATH
          remote-path: /
