# This is a basic workflow to help you get started with Actions
name: Deploy Databricks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches:
      - "dev"
      - "releases/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload src artifacts
        uses: actions/upload-artifact@v3
        with:
          name: src_artifacts
          path: databricks/src/
          if-no-files-found: error
          retention-days: 1

  deploy-dev:
    name: Deploy Dev Environment
    needs: publish_artifacts
    uses: ./.github/workflows/deploy-databricks.yml
    with:
      env_name: dev
    secrets:
      host: ${{ secrets.DATABRICKS_HOST }}
      pat: ${{ secrets.DATABRICKS_PAT }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-qa:
    name: Deploy QA Environment
    needs: deploy-dev
    uses: ./.github/workflows/deploy-databricks.yml
    with:
      env_name: qa
    secrets:
      host: ${{ secrets.DATABRICKS_HOST }}
      pat: ${{ secrets.DATABRICKS_PAT }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-prod:
    name: Deploy Production Environment
    needs: deploy-qa
    uses: ./.github/workflows/deploy-databricks.yml
    with:
      env_name: production
    secrets:
      host: ${{ secrets.DATABRICKS_HOST }}
      pat: ${{ secrets.DATABRICKS_PAT }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
